import { test, expect } from '@playwright/test'

test('onboarding and workout logging flow', async ({ page }) => {
  await page.goto('./')
  await expect(page.getByText('IRONLOG').first()).toBeVisible()
  await page.getByRole('button',{name:/get started|aloita/i}).click()
  await page.getByRole('button',{name:'SELECT'}).click()
  await page.getByRole('button',{name:/start training|aloita treenaaminen/i}).click()
  await expect(page.getByRole('button',{name:/start workout|aloita treeni/i})).toBeVisible()
  await page.getByRole('button',{name:/start workout|aloita treeni/i}).click()
  await page.getByLabel('Set 1 weight').fill('80')
  await page.getByLabel('Set 1 reps').fill('8')
  await page.getByRole('button',{name:'✓'}).first().click()
  await expect(page.getByText(/^(REST|TAUKO)$/)).toBeVisible()
})

test('selected plan, future Wednesday, saved days and complete workout history', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.clock.setFixedTime(new Date('2026-09-15T10:00:00Z'))
  await page.goto('./')
  await page.getByRole('button', { name: /get started/i }).click()
  await page.getByRole('button', { name: 'SELECT' }).click()
  await page.getByRole('button', { name: /start training/i }).click()
  await expect(page.locator('.selected-plan strong')).toHaveText('Chest, Back + Arms')
  await page.getByRole('button', { name: '02 Programs' }).click()
  await expect(page.locator('.active-program .program-preview')).toHaveAttribute('open', '')
  await expect(page.locator('.active-program .plan-workout')).toHaveCount(3)
  await page.getByRole('button', { name: '03 Calendar' }).click()
  await page.getByLabel('Go to date').fill('2026-09-23')
  await expect(page.locator('.calendar-detail h2')).toHaveText('Upper B · Back + Arms')
  await expect(page.locator('.calendar-detail .plan-exercises li')).toHaveCount(6)
  await expect(page.getByRole('button', { name: 'Lat Pulldown', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Do this workout now' })).toHaveCount(0)
  await page.screenshot({ path: 'test-results/calendar-mobile.png', fullPage: true })
  await page.getByRole('button', { name: 'Next month' }).click()
  await expect(page.locator('.calendar-toolbar h2')).toHaveText('October 2026')
  await page.getByRole('button', { name: 'Previous month' }).click()
  await page.getByRole('button', { name: '01 Today' }).click()
  await page.getByRole('button', { name: 'START WORKOUT' }).click()
  await page.getByLabel('Set 1 weight').fill('42.5')
  await page.getByLabel('Set 1 reps').fill('11')
  await page.getByRole('button', { name: '✓' }).first().click()
  await expect(page.getByRole('status')).toHaveText('Saved on this device')
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: 'Finish', exact: true }).click()
  await page.getByRole('button', { name: /View history/ }).click()
  await expect(page.locator('.workout-record')).toHaveCount(1)
  await page.locator('.workout-record summary').click()
  await expect(page.locator('.logged-exercise').first().getByRole('cell', { name: '42.5', exact: true })).toBeVisible()
  await expect(page.locator('.logged-exercise').first().getByRole('cell', { name: '11', exact: true })).toBeVisible()
  await page.screenshot({ path: 'test-results/history-mobile.png', fullPage: true })
  await page.reload()
  await page.getByRole('button', { name: '04 History' }).click()
  await expect(page.locator('.workout-record')).toHaveCount(1)
  await page.getByRole('button', { name: '03 Calendar' }).click()
  await expect(page.locator('[data-date="2026-09-15"]')).toHaveClass(/day-complete/)
  await page.getByLabel('Go to date').fill('2026-09-23')
  await expect(page.locator('.calendar-detail h2')).toHaveText('Upper B · Back + Arms')
  await page.locator('.schedule-settings summary').click()
  await page.getByRole('button', { name: 'Wednesday', exact: true }).click()
  await page.getByRole('button', { name: 'Thursday', exact: true }).click()
  await expect(page.locator('.calendar-detail h2')).toHaveText('Rest day')
  await page.reload()
  await page.getByRole('button', { name: '03 Calendar' }).click()
  await page.getByLabel('Go to date').fill('2026-09-24')
  await expect(page.locator('.calendar-detail h2')).toHaveText('Upper B · Back + Arms')
  await page.getByRole('button', { name: '02 Programs' }).click()
  await page.locator('.program-card').filter({ has: page.getByRole('heading', { name: 'Beginner Full Body', exact: true }) }).getByRole('button', { name: 'Use program', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Calendar', exact: true })).toBeVisible()
  await page.reload()
  await expect(page.locator('.selected-plan strong')).toHaveText('Beginner Full Body')
  for (const width of [320, 390, 1280]) {
    await page.setViewportSize({ width, height: 900 })
    await page.getByRole('button', { name: '02 Programs' }).click()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)
    await page.getByRole('button', { name: '03 Calendar' }).click()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)
    await page.getByRole('button', { name: '04 History' }).click()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)
  }
  expect(errors).toEqual([])
})
