import type { Language } from './types'

const t = {
  en: {
    calendar:'Calendar', selectedPlan:'Selected plan', viewPlan:'View plan', viewCalendar:'View calendar', nextWorkout:'Next workout', upcoming:'Coming up', restDay:'Rest day', scheduled:'Planned', completed:'Completed', inProgress:'In progress', notLogged:'Not logged', workoutLog:'Workout log', exerciseRecords:'Exercise records', workoutCount:'Workouts', noMatches:'No workouts match these filters.', searchWorkouts:'Search workouts or exercises', fromDate:'From date', toDate:'To date', clearFilters:'Clear filters', loggedSets:'Logged sets', warmup:'Warm-up', skipped:'Not completed', notes:'Notes', noWorkouts:'No finished workouts yet. Finish a workout to see its date, exercises, weights and reps here.', scheduleHelp:'Workouts rotate across your selected days. Missing a workout does not shift future dates.', scheduleChanged:'Changing the plan or training days restarts the schedule this week. Saved workouts stay unchanged.', planStarts:'Current schedule starts', previousMonth:'Previous month', nextMonth:'Next month', goToDate:'Go to date', browsePrograms:'Choose a plan', resumeWorkout:'Resume workout', recordedOnDay:'Workouts on this date', noPlanOnDate:'No planned workout on this date.', startThisWorkout:'Do this workout now', previewOnly:'Future workout preview', allWorkouts:'All workouts', minutes:'min', session:'Session', sets:'sets', details:'Details', trainingDaysHelp:'Choose your training days. The calendar uses the order Monday to Sunday.',

    today:'Today', programs:'Programs', history:'History', profile:'Profile', startWorkout:'Start workout', lastSession:'Last session', nextTarget:'Next target', exercises:'exercises', workingSets:'working sets', rest:'REST', skip:'Skip', instructions:'Instructions', finish:'Finish workout', complete:'Work complete', duration:'Duration', totalVolume:'Total volume', prs:'Personal records', data:'Data', export:'Export my data', import:'Import data', delete:'Delete all data', language:'Language', units:'Units', autoRest:'Automatic rest timer', selectProgram:'Use program', createProgram:'Create program', addExercise:'Add exercise', save:'Save', cancel:'Cancel', estimated1rm:'Estimated 1RM', noHistory:'No history yet', viewHistory:'View history', previous:'Previous', done:'Done', set:'Set', reps:'Reps', how:'How to perform', mistakes:'Common mistakes', best:'Your best', trainingDays:'Training days', choose:'Choose your program', getStarted:'Get started', startTraining:'Start training', recommended:'Recommended', plateCalculator:'Plate calculator'
  },
  fi: {
    calendar:'Kalenteri', selectedPlan:'Valittu ohjelma', viewPlan:'Näytä ohjelma', viewCalendar:'Näytä kalenteri', nextWorkout:'Seuraava treeni', upcoming:'Tulevat treenit', restDay:'Lepopäivä', scheduled:'Suunniteltu', completed:'Valmis', inProgress:'Kesken', notLogged:'Ei kirjattu', workoutLog:'Treenihistoria', exerciseRecords:'Liike-ennätykset', workoutCount:'Treenejä', noMatches:'Näillä rajauksilla ei löydy treenejä.', searchWorkouts:'Etsi treeniä tai liikettä', fromDate:'Alkupäivä', toDate:'Loppupäivä', clearFilters:'Tyhjennä rajaukset', loggedSets:'Kirjatut sarjat', warmup:'Lämmittely', skipped:'Ei tehty', notes:'Muistiinpanot', noWorkouts:'Ei vielä valmiita treenejä. Kun lopetat treenin, näet täällä päivän, liikkeet, painot ja toistot.', scheduleHelp:'Treenit kiertävät valitseminasi päivinä. Väliin jäänyt treeni ei siirrä tulevia päiviä.', scheduleChanged:'Ohjelman tai treenipäivien vaihto aloittaa kierron uudelleen tältä viikolta. Tallennetut treenit säilyvät.', planStarts:'Nykyinen aikataulu alkaa', previousMonth:'Edellinen kuukausi', nextMonth:'Seuraava kuukausi', goToDate:'Siirry päivään', browsePrograms:'Valitse ohjelma', resumeWorkout:'Jatka treeniä', recordedOnDay:'Tämän päivän treenit', noPlanOnDate:'Tälle päivälle ei ole suunniteltua treeniä.', startThisWorkout:'Tee tämä treeni nyt', previewOnly:'Tulevan treenin esikatselu', allWorkouts:'Kaikki treenit', minutes:'min', session:'Treeni', sets:'sarjaa', details:'Tiedot', trainingDaysHelp:'Valitse treenipäivät. Kalenterin järjestys on maanantaista sunnuntaihin.',

    today:'Tänään', programs:'Ohjelmat', history:'Historia', profile:'Profiili', startWorkout:'Aloita treeni', lastSession:'Edellinen treeni', nextTarget:'Seuraava tavoite', exercises:'liikettä', workingSets:'työsarjaa', rest:'TAUKO', skip:'Ohita', instructions:'Ohjeet', finish:'Lopeta treeni', complete:'Treeni valmis', duration:'Kesto', totalVolume:'Kokonaisvolyymi', prs:'Omat ennätykset', data:'Data', export:'Vie tiedot', import:'Tuo tiedot', delete:'Poista kaikki tiedot', language:'Kieli', units:'Yksiköt', autoRest:'Automaattinen taukoajastin', selectProgram:'Ota käyttöön', createProgram:'Luo ohjelma', addExercise:'Lisää liike', save:'Tallenna', cancel:'Peruuta', estimated1rm:'Arvioitu 1RM', noHistory:'Ei historiaa vielä', viewHistory:'Näytä historia', previous:'Edellinen', done:'Valmis', set:'Sarja', reps:'Toistot', how:'Suoritustekniikka', mistakes:'Yleiset virheet', best:'Paras tulos', trainingDays:'Treenipäivät', choose:'Valitse ohjelma', getStarted:'Aloita', startTraining:'Aloita treenaaminen', recommended:'Suositus', plateCalculator:'Levylaskuri'
  }
} as const

export function translate(lang: Language, key: keyof typeof t.en) { return t[lang][key] }
